# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daff/PycharmProjects/pythonProject/Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 514)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/daff/PycharmProjects/pythonProject/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 301, 31))
        self.label.setObjectName("label")
        self.listDataShow = QtWidgets.QListWidget(self.centralwidget)
        self.listDataShow.setGeometry(QtCore.QRect(435, 70, 221, 381))
        self.listDataShow.setObjectName("listDataShow")
        self.btn_ShowGraph = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ShowGraph.setGeometry(QtCore.QRect(70, 340, 83, 25))
        self.btn_ShowGraph.setObjectName("btn_ShowGraph")
        self.spin_Date = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_Date.setGeometry(QtCore.QRect(120, 200, 131, 26))
        self.spin_Date.setMaximum(23)
        self.spin_Date.setObjectName("spin_Date")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 160, 191, 31))
        self.label_2.setObjectName("label_2")
        self.btn_SaveGraph = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SaveGraph.setGeometry(QtCore.QRect(200, 340, 114, 25))
        self.btn_SaveGraph.setObjectName("btn_SaveGraph")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 30, 221, 31))
        self.label_3.setObjectName("label_3")
        self.btn_Analisis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Analisis.setGeometry(QtCore.QRect(130, 270, 111, 25))
        self.btn_Analisis.setObjectName("btn_Analisis")
        self.btn_SelectDirectory = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SelectDirectory.setGeometry(QtCore.QRect(160, 80, 86, 42))
        self.btn_SelectDirectory.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_SelectDirectory.setAutoDefault(False)
        self.btn_SelectDirectory.setDefault(False)
        self.btn_SelectDirectory.setFlat(False)
        self.btn_SelectDirectory.setObjectName("btn_SelectDirectory")
        self.lbl_statusAnalisis = QtWidgets.QLabel(self.centralwidget)
        self.lbl_statusAnalisis.setGeometry(QtCore.QRect(260, 270, 131, 31))
        self.lbl_statusAnalisis.setText("")
        self.lbl_statusAnalisis.setObjectName("lbl_statusAnalisis")
        self.lbl_NombreArchivo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_NombreArchivo.setGeometry(QtCore.QRect(90, 300, 311, 31))
        self.lbl_NombreArchivo.setText("")
        self.lbl_NombreArchivo.setObjectName("lbl_NombreArchivo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analisadorinador"))
        self.label.setText(_translate("MainWindow", "Seleccione la carpeta donde estan los datos"))
        self.btn_ShowGraph.setText(_translate("MainWindow", "Ver grafico"))
        self.label_2.setText(_translate("MainWindow", "Lapso de tiempo a analizar"))
        self.btn_SaveGraph.setText(_translate("MainWindow", "Guardar grafico"))
        self.label_3.setText(_translate("MainWindow", "Seleccione la fecha de los datos"))
        self.btn_Analisis.setText(_translate("MainWindow", "Analisar datos"))
        self.btn_SelectDirectory.setText(_translate("MainWindow", "Seleccionar \n"
" carpeta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
